// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-dev/abv-sample-sdk/models/components"
	"net/http"
)

type GetRequestFromEventLogRequest struct {
	// The ID of the request to retrieve.
	RequestID string `pathParam:"style=simple,explode=false,name=requestID"`
}

func (o *GetRequestFromEventLogRequest) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

type GetRequestFromEventLogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *components.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UnboundedRequest *components.UnboundedRequest
}

func (o *GetRequestFromEventLogResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRequestFromEventLogResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetRequestFromEventLogResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRequestFromEventLogResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetRequestFromEventLogResponse) GetUnboundedRequest() *components.UnboundedRequest {
	if o == nil {
		return nil
	}
	return o.UnboundedRequest
}
