// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-dev/abv-sample-sdk/models/components"
	"net/http"
)

type GetValidEmbedAccessTokensResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *components.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Classes []components.EmbedToken
}

func (o *GetValidEmbedAccessTokensResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetValidEmbedAccessTokensResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetValidEmbedAccessTokensResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetValidEmbedAccessTokensResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetValidEmbedAccessTokensResponse) GetClasses() []components.EmbedToken {
	if o == nil {
		return nil
	}
	return o.Classes
}
