// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks-dev/abv-sample-sdk/models/components"
	"net/http"
)

type QueryEventLogRequest struct {
	// The filter to apply to the query.
	Filters *components.Filters `queryParam:"serialization=json,name=filters"`
}

func (o *QueryEventLogRequest) GetFilters() *components.Filters {
	if o == nil {
		return nil
	}
	return o.Filters
}

type QueryEventLogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Error *components.Error
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Classes []components.BoundedRequest
}

func (o *QueryEventLogResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *QueryEventLogResponse) GetError() *components.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *QueryEventLogResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *QueryEventLogResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *QueryEventLogResponse) GetClasses() []components.BoundedRequest {
	if o == nil {
		return nil
	}
	return o.Classes
}
